include:
  - project: 'controls/reports/ci_templates'
    ref: master
    file: 'python3/dls_py3_template.yml'


stages:
  - test
  - deploy

deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
    - if: '$CI_COMMIT_TAG'
  trigger: controls/kubernetes/coniql
  variables:
    CI_UPSTREAM_BRANCH: '$CI_COMMIT_REF_NAME'
    CI_UPSTREAM_TAG: '$CI_COMMIT_TAG'
