language: python
python:
  - "3.7"
  - "3.8"

install:
  - env
  - pip install coveralls
  - pipenv install --dev
  - ls -al ${VIRTUAL_ENV}/lib/python${TRAVIS_PYTHON_VERSION}/site-packages
  - ls -al ${VIRTUAL_ENV}/bin
  - python setup.py bdist_wheel

script:
  - pipenv run tests
  - pipenv run docs

after_script:
  - coveralls

env:
  global:
    # This sets SOURCE_DATE_EPOCH to the date of the last commit for reproducible builds
    # See here for more info : https://reproducible-builds.org/
    - SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)

deploy:
  provider: pypi
  edge: true
  user: "__token__"
  password:
    secure: "OVX9LiSyw7A3RdFdLMGbmQ9x5lL10iyq5m6omLKrdrj3emTmaPlG3ldWm67nk+qVPmf2hXvHODMCXjTB5aRQ8GoOrWZV5BEd6a5rU/F9MSU/Ivavh6AzPAE0KpJ4pCFkuIi/qimqpFzgcoCCKEJecEvLMk1AJk+pAdrZUWbBjZnWUG4vfC6FJrLZAqxjrOXNxqwWjrZwzMlSIvFTG69bGgvGdyfzAiLDPR+mf+eP82KAgTfcgYXdxmH2F9FVFAfP9a6Ow9O+vWQ8Z0TST0yO1i/+NQIe+WV5QtSamJ35j5TcfeI4VOizuY2b2EcDwsRxXBZtNyOuPkPR3rkJ2lfidzlDHCvYO+NTZJLY33KIrHC8jlxdoAQ5/sk+EmlejcWjd7i7/pfkl4lNyQFpuIYWZuEw0v9jpfnQw8xHE/YlgIPy5ukmRVgTBS6tLZ5agAXXj48H1P9o2FuqABKQnVtTEovRvd2Cuzx1gVrBezDoGuxfS0iF/FR0T9n27Vtd36ijhWOPYiobxXxh/NwNtUmeKtFwxZemgqR8jkSI1jehPlwMbUx72vYKLs2+n0LSKLLfenHashMQ2VHGOOQ+csgUNMkOHbMbRjfTDtDfLWJD0+MAzoBs1GTZV8oc+RNR64x7k7iSbq6sAhfxb/keTyGNIsc6ILr5BSy8FdIXyVboTYY="
  distributions: "sdist bdist_wheel"
  # Use the same version of wheel as inside DLS
  wheel_version: "0.33.1"
  skip_existing: true
  on:
    tags: true