trigger:
  type: device.channel.ca.CaEnum
  pv: $(prefix)
  timeout: 300 # TODO: Temporary, dynamic timeout needed

status:
  type: device.channel.ca.CaString
  pv: $(prefix)Status_RBV

state:
  type: device.channel.ca.CaString
  pv: $(prefix)State_RBV

message:
  type: device.channel.ca.CaString
  pv: $(prefix)Message_RBV
