# Deploys a single Coniql server and an EPICS IOC in a Pod, on a static IP address
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coniql-performance-test
  labels:
    app: coniql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coniql
  template:
    metadata:
      labels:
        app: coniql
    spec:
      containers:
      - name: coniql
        image: ghcr.io/diamondlightsource/coniql:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 1
            memory: 2Gi
      - name: ioc
        image: gcr.io/diamond-privreg/controls/coniql/ioc:latest
        stdin: true
        tty: true
        resources:
          limits:
            cpu: 1
            memory: 2Gi

---

apiVersion: v1
kind: Service
metadata:
  name: coniql-performance-test-service
  labels:
    app: coniql
spec:
  type: ClusterIP
  ports:
    - name: coniqlport
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: coniql
